<h1 style = "color:Brown">Objectives</h1>

### 1. Loading data.
### 2. Checking for missing values.
### 3. Splitting the data in to train set and test set.




<h2 style = "color:green">Loading Data</h2>

In [9]:
# Load the data from external flat file - use pandas.read_csv() or pandas.read_excel()
import pandas as pd
df1 = pd.read_csv("churn-Modelling.csv")
print(type(df1))
print(df1.shape)
print(df1.head())

<class 'pandas.core.frame.DataFrame'>
(10000, 7)
   CreditScore  Age  Tenure    Balance  HasCrCard     Salary  Exited
0          619   42       2       0.00          1  101348.88       1
1          608   41       1   83807.86          0  112542.58       0
2          502   42       8  159660.80          1  113931.57       1
3          699   39       1       0.00          0   93826.63       0
4          850   43       2  125510.82          1   79084.10       0


In [22]:
# Load the data from sklearn.datasets - load_iris(), load_diabetes(), load_digits(), load_linnerud(), load_wine(), load_breast_cancer()
from sklearn.datasets import load_iris
ds = load_iris()
print(type(ds))

x = ds.data
print(x.shape)
print(type(x))
print(x[0:5])
print(ds.feature_names)

y = ds.target
print(type(y))
print(y[0:5])
print(y[145:150])
print(ds.target_names)

<class 'sklearn.utils._bunch.Bunch'>
(150, 4)
<class 'numpy.ndarray'>
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
<class 'numpy.ndarray'>
[0 0 0 0 0]
[2 2 2 2 2]
['setosa' 'versicolor' 'virginica']


In [49]:
#loading the data as input and output separetly as ndobject
# Parameter return_X_y=True returns the data set as separate input and output nupy arrays
X, y = load_iris(return_X_y = True) 

print(type(X))
print(X[3:5])

print(type(y))
print(y[5:10])

<class 'numpy.ndarray'>
[[4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
<class 'numpy.ndarray'>
[0 0 0 0 0]


In [46]:
# Parameter as_frame=True returns the data as a dataframe.
X, y = load_iris(return_X_y = True , as_frame =True) 

print(type(X))
print(X[0:5])

print(type(y))
print(y[0:3])

<class 'pandas.core.frame.DataFrame'>
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2
<class 'pandas.core.series.Series'>
0    0
1    0
2    0
Name: target, dtype: int32


<h2 style = "color:green">pandas.isna(object)</h2>

### Detects missing values.
### Returns a boolen object of same size.
### None and np.NaN are mapped True values. Everything else gets mapped to False values.

In [30]:
df1.isna().sum()

CreditScore    0
Age            0
Tenure         0
Balance        0
HasCrCard      0
Salary         0
Exited         0
dtype: int64

In [48]:
x = df1.drop("Exited", axis = 1)
y = df1["Exited"]
print(x.head(2))
print(y.tail())

   CreditScore  Age  Tenure   Balance  HasCrCard     Salary
0          619   42       2      0.00          1  101348.88
1          608   41       1  83807.86          0  112542.58
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, dtype: int64


<h2 style = "color:green">x_train, x_test, y_tran, y_test = train_test_split(x, y, test_size)</h2>

### Defined in sklearn.model_selection
### test_size attribute decides the proportion of split

In [43]:
# Split the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(8000, 6)
(8000,)
(2000, 6)
(2000,)
